name: Third Project

on: push

jobs:
  ARTIFACT_JOB:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: Install Cowsay
      run: sudo apt-get install cowsay -y

    - name: Run Cowsay Command
      run: cowsay -f dragon "Run for cover, I'm a dragon" >> dragon.txt
    
    - name: upload the artifact file
      uses: actions/upload-artifact@v4
      with:
        name: dragon-txt-file
        path: dragon.txt
  Job2:
    needs: ARTIFACT_JOB 
    runs-on: ubuntu-latest
    steps:
        - name: Download Artifact
          uses: actions/download-artifact@v4
          with:
            name: dragon-txt-file
            
        - name: Test file exist
          run: grep -i "dragon" dragon.txt
  Job3:
    needs: Job2
    runs-on: ubuntu-latest
    steps:
  
        - name: Download Artifact
          uses: actions/download-artifact@v4
          with:
            name: dragon-txt-file
            
        - name: Read File
          run: cat dragon.txt